### PR TITLE
Backend update

### PR DESCRIPTION
**Pull request by zimo27**
Upload existing backend files, initialize requirements and server

### CODE REVIEW

**Comment by champion-chenpeng** [comment]
looks good to me.
But I suggest adding the api call in the frontend project to test it.

**Comment by champion-chenpeng** [comment]
I've noticed that I'm missing some dependencies, such as langchain. Could we create a package management file, like requirements.yml, to ensure a consistent Python environment? Additionally, let's update the README.md to include instructions on how to install these dependencies.

**Comment by champion-chenpeng** [comment]
It is good to have a requirements.txt to lock the environment. I think we can add it to the main README.md

**Review by katiehsieh — APPROVED** [review]
Looks good to me!

**Pull request merged**
