### PR TITLE
Scroll bar

### PR DESCRIPTION
**Pull request by katiehsieh**
Added scrollable messages. When a new message is sent, it scrolls to the bottom to the newest message. Also cleaned up CSS files and updated colors.

Home page:
Screenshot 2024-02-26 at 4 02 14 PM

Chat messages start from bottom above message box:
Screenshot 2024-02-26 at 4 03 18 PM

Messages become scrollable after filling up the screen:
Screenshot 2024-02-26 at 4 04 31 PM

Helpful resources:
- [Pin scrolling to bottom](https://css-tricks.com/books/greatest-css-tricks/pin-scrolling-to-bottom/)
- [scrollIntoView](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView)

### CODE REVIEW

**Comment by zimo27** [comment]
Looks good to me

**Comment by champion-chenpeng** [comment]
It looks good to me

**Review by champion-chenpeng — APPROVED** [review]
lgtm

**Review by zimo27 — APPROVED** [review]
Looks good

**Pull request merged**
