### PR TITLE
Add GitHub action for running tests

### PR DESCRIPTION
**Pull request by katiehsieh**
Runs tests in frontend directory for CI.

### CODE REVIEW

**Comment by champion-chenpeng** [comment]
Overall, everything appears to be in good shape as it successfully passed the checks. However, I did notice some warnings suggesting the use of Node.js 20. Here's a screenshot for reference:

Screenshot 2024-02-22 at 9 12 52 AM

I'm not entirely certain how to incorporate the necessary changes into the .yml file, but perhaps this snippet could provide some guidance:

image

Let's explore this further to ensure we're utilizing Node.js 20 as recommended.

**Review by champion-chenpeng — COMMENTED** [review]
Looks good to me

**Comment by katiehsieh** [comment]
Finished updating the .yml file with no more warnings.

**Review by champion-chenpeng — APPROVED** [review]
Good!

**Pull request merged**
